---
version: 1.4.10-6
default-factions-plugin: FactionsPro
enable-multiworld-chat: false
groups:
  Guest:
    chat: '&f{clan} &7[&fＧｕｅｓｔ&7]&a {display_name} &7→ &f{msg}'
    nametag: '&7[&fＧｕｅｓｔ&7] &a{display_name}'
    worlds: []
  VIP1:
    nametag: '{clan} &a&l☘&eVIP1&a☘&d {display_name}'
    chat: '{clan} &a&l☘&eVIP1&a☘&d {display_name} &7→&6 {msg}'
    worlds: []
  VIP2:
    nametag: '{clan} &a&l☘&eVIP2&a☘&d {display_name}'
    chat: '{clan} &a&l☘&eVIP2&a☘&d {display_name} &7→&6 {msg}'
    worlds: []
  VIP3:
    nametag: '{clan} &a&l☘&eVIP3&a☘&d {display_name}'
    chat: '{clan} &a&l☘&eVIP3&a☘&d {display_name} &7→&6 {msg}'
    worlds: []
  VIP4:
    nametag: '{clan} &a&l☘&eVIP4&a☘&d {display_name}'
    chat: '{clan} &a&l☘&eVIP4&a☘&d {display_name} &7→&6 {msg}'
    worlds: []
  VIP5:
    nametag: '{clan} &a&l☘&eVIP5&a☘&d {display_name}'
    chat: '{clan} &a&l☘&eVIP5&a☘&d {display_name} &7→&6 {msg}'
    worlds: []
  VIP6:
    nametag: '{clan} &a&l☘&eVIP6&a☘&d {display_name}'
    chat: '{clan} &a&l☘&eVIP6&a☘&d {display_name} &7→&6 {msg}'
    worlds: []
  VIP7:
    nametag: '{clan} &a&l☘&eVIP7&a☘&d {display_name}'
    chat: '{clan} &a&l☘&eVIP7&a☘&d {display_name} &7→&6 {msg}'
    worlds: []
  Owner:
    nametag: '&8&l[Owner]&f&r {display_name}'
    chat: '&8&l[Owner]&f&r {display_name} &7> {msg}'
  Admin:
    nametag: '&8&l[Admin]&f&r {display_name}'
    chat: '&8&l[Admin]&f&r {display_name} &7> {msg}'
  Op:
    nametag: §l●§3{clan}§b•§b⊰⊹§dOP§b⊹⊱§b• §r{display_name}
    chat: §l●§3{clan}§b•§b⊰⊹§dOP§b⊹⊱§b• §r{display_name} §b☛§b§l{msg}
  Police:
    chat: §3{clan}§b§e✤§aCảɴʜ Sáᴛ§e✤§r {display_name} §a☛{msg}
    nametag: '&8&l[Police]&f&r {display_name}'
  YouTube:
    nametag: §l§aYouTube
    chat: '&8&l[YouTube]&f&r {display_name} &7> {msg}'
...
