---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: newvid
  X: 94.321200
  "Y": 24.000000
  Z: 4.919900
  Yaw: 344.873779
  Pitch: 71.201782
...
