---
marker:
  1: 2000
database:
  phuongaz:
    block: 0
    level: 0
  dbgamingvn2:
    block: 4841
    level: 1
  BlackPMFury:
    block: 0
    level: 0
  SeaLonggaming:
    block: 162
    level: 0
  Jose9543:
    block: 2018
    level: 1
  Kayne6162:
    block: 11663
    level: 1
  AiLaNhan:
    block: 7070
    level: 1
  ICECream1073:
    block: 4291
    level: 1
  Kedoki2579:
    block: 12365
    level: 1
  Taizaxua5652:
    block: 2953
    level: 1
  Hreinas:
    block: 3278
    level: 1
  HKYT19:
    block: 218
    level: 0
  BananiK6406:
    block: 10854
    level: 1
  haongu1592k8:
    block: 3588
    level: 1
  HiepSiCoDon:
    block: 162
    level: 0
  Datsiudz:
    block: 15962
    level: 1
  joLungLay:
    block: 0
    level: 0
  MinhKha12:
    block: 11049
    level: 1
  ahihiz:
    block: 36062
    level: 1
  MinhPhuc2692:
    block: 578
    level: 0
  JustThais2008:
    block: 150
    level: 0
  huy30cm:
    block: 13836
    level: 1
  BananiKYT:
    block: 0
    level: 0
  ShiftyAmoeba829:
    block: 0
    level: 0
  fitgof14:
    block: 19
    level: 0
  JackTHNGaming41:
    block: 1552
    level: 0
  Kem_Onii_chann:
    block: 409
    level: 0
  NgLamVN:
    block: 56
    level: 0
  BinRongVN:
    block: 1005
    level: 0
  ShadowMarlin319:
    block: 3
    level: 0
  TRUONGMC95:
    block: 0
    level: 0
  DEVILxMC2768:
    block: 195
    level: 0
  Tuankhanh01:
    block: 1634
    level: 0
  HuyAsics:
    block: 28
    level: 0
  ngothienquan860:
    block: 89
    level: 0
  meonho1502:
    block: 0
    level: 0
  NonHercules2394:
    block: 21
    level: 0
  Cacutexiu:
    block: 3759
    level: 1
  PhoPhuc:
    block: 732
    level: 0
  Dz_gaming66:
    block: 84
    level: 0
  Vu_RoSe:
    block: 5668
    level: 1
  tapL050:
    block: 142
    level: 0
...
