---
xp:
- blackpmfury: 0
  sealonggaming: 19
  jose9543: 77
  kayne6162: 6
  phuongaz: 0
  ailanhan: 12
  icecream1073: 79
  kedoki2579: 447
  dbgamingvn2: 126
  taizaxua5652: 11
  haongu1592k8: 3
  hreinas: 278
  hkyt19: 61
  bananik6406: 30
  hiepsicodon: 99
  datsiudz: 26
  jolunglay: 0
  minhkha12: 255
  ahihiz: 41
  minhphuc2692: 1
  justthais2008: 39
  huy30cm: 245
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 1
  jackthngaming41: 69
  kem_onii_chann: 70
  nglamvn: 0
  binrongvn: 50
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 44
  tuankhanh01: 40
  huyasics: 5
  ngothienquan860: 5
  meonho1502: 0
  nonhercules2394: 20
  cacutexiu: 4
  phophuc: 2
  dz_gaming66: 4
- blackpmfury: 0
  sealonggaming: 0
  jose9543: 1
  kayne6162: 45
  phuongaz: 0
  ailanhan: 0
  icecream1073: 15
  kedoki2579: 62
  dbgamingvn2: 8
  taizaxua5652: 0
  haongu1592k8: 0
  hreinas: 170
  hkyt19: 0
  bananik6406: 39
  hiepsicodon: 0
  datsiudz: 0
  jolunglay: 0
  minhkha12: 4
  ahihiz: 0
  minhphuc2692: 0
  justthais2008: 0
  huy30cm: 10
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 0
  jackthngaming41: 0
  kem_onii_chann: 0
  nglamvn: 1
  binrongvn: 44
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 0
  tuankhanh01: 0
  huyasics: 0
  ngothienquan860: 0
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 0
  phophuc: 0
  dz_gaming66: 0
- blackpmfury: 0
  sealonggaming: 0
  jose9543: 0
  kayne6162: 0
  phuongaz: 0
  ailanhan: 0
  icecream1073: 0
  kedoki2579: 0
  dbgamingvn2: 0
  taizaxua5652: 0
  haongu1592k8: 0
  hreinas: 0
  hkyt19: 0
  bananik6406: 0
  hiepsicodon: 0
  datsiudz: 0
  jolunglay: 0
  minhkha12: 0
  ahihiz: 0
  minhphuc2692: 0
  justthais2008: 0
  huy30cm: 0
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 0
  jackthngaming41: 0
  kem_onii_chann: 0
  nglamvn: 0
  binrongvn: 0
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 0
  tuankhanh01: 0
  huyasics: 0
  ngothienquan860: 0
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 0
  phophuc: 0
  dz_gaming66: 0
- blackpmfury: 0
  sealonggaming: 18
  jose9543: 52
  kayne6162: 381
  phuongaz: 0
  ailanhan: 29
  icecream1073: 575
  kedoki2579: 97
  dbgamingvn2: 248
  taizaxua5652: 13
  haongu1592k8: 156
  hreinas: 3
  hkyt19: 7
  bananik6406: 175
  hiepsicodon: 3
  datsiudz: 253
  jolunglay: 0
  minhkha12: 242
  ahihiz: 170
  minhphuc2692: 21
  justthais2008: 4
  huy30cm: 488
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 0
  jackthngaming41: 156
  kem_onii_chann: 21
  nglamvn: 4
  binrongvn: 1
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 9
  tuankhanh01: 54
  huyasics: 0
  ngothienquan860: 5
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 50
  phophuc: 51
  dz_gaming66: 1
- blackpmfury: 0
  sealonggaming: 0
  jose9543: 0
  kayne6162: 0
  phuongaz: 0
  ailanhan: 0
  icecream1073: 0
  kedoki2579: 0
  dbgamingvn2: 0
  taizaxua5652: 0
  haongu1592k8: 0
  hreinas: 0
  hkyt19: 0
  bananik6406: 0
  hiepsicodon: 0
  datsiudz: 0
  jolunglay: 0
  minhkha12: 0
  ahihiz: 0
  minhphuc2692: 0
  justthais2008: 0
  huy30cm: 0
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 0
  jackthngaming41: 0
  kem_onii_chann: 0
  nglamvn: 0
  binrongvn: 0
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 0
  tuankhanh01: 0
  huyasics: 0
  ngothienquan860: 0
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 0
  phophuc: 0
  dz_gaming66: 0
- blackpmfury: 0
  sealonggaming: 0
  jose9543: 0
  kayne6162: 0
  phuongaz: 0
  ailanhan: 0
  icecream1073: 0
  kedoki2579: 0
  dbgamingvn2: 0
  taizaxua5652: 0
  haongu1592k8: 0
  hreinas: 0
  hkyt19: 0
  bananik6406: 0
  hiepsicodon: 0
  datsiudz: 0
  jolunglay: 0
  minhkha12: 0
  ahihiz: 0
  minhphuc2692: 0
  justthais2008: 0
  huy30cm: 0
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 0
  jackthngaming41: 0
  kem_onii_chann: 0
  nglamvn: 0
  binrongvn: 0
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 0
  tuankhanh01: 0
  huyasics: 0
  ngothienquan860: 0
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 0
  phophuc: 0
  dz_gaming66: 0
- blackpmfury: 0
  sealonggaming: 130
  jose9543: 271
  kayne6162: 24
  phuongaz: 0
  ailanhan: 128
  icecream1073: 30
  kedoki2579: 260
  dbgamingvn2: 88
  taizaxua5652: 73
  haongu1592k8: 23
  hreinas: 218
  hkyt19: 2
  bananik6406: 476
  hiepsicodon: 1
  datsiudz: 395
  jolunglay: 0
  minhkha12: 52
  ahihiz: 26
  minhphuc2692: 21
  justthais2008: 11
  huy30cm: 151
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 1
  jackthngaming41: 50
  kem_onii_chann: 14
  nglamvn: 0
  binrongvn: 37
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 6
  tuankhanh01: 7
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 8
  phophuc: 7
  dz_gaming66: 2
- blackpmfury: 0
  sealonggaming: 0
  jose9543: 0
  kayne6162: 0
  phuongaz: 0
  ailanhan: 0
  icecream1073: 0
  kedoki2579: 0
  dbgamingvn2: 0
  taizaxua5652: 0
  haongu1592k8: 0
  hreinas: 0
  hkyt19: 0
  bananik6406: 0
  hiepsicodon: 0
  datsiudz: 0
  jolunglay: 0
  minhkha12: 0
  ahihiz: 0
  minhphuc2692: 0
  justthais2008: 0
  huy30cm: 0
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 0
  jackthngaming41: 0
  kem_onii_chann: 0
  nglamvn: 0
  binrongvn: 0
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 0
  tuankhanh01: 0
  huyasics: 0
  ngothienquan860: 0
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 0
  phophuc: 0
  dz_gaming66: 0
- blackpmfury: 0
  sealonggaming: 0
  jose9543: 0
  kayne6162: 0
  phuongaz: 0
  ailanhan: 0
  icecream1073: 0
  kedoki2579: 0
  dbgamingvn2: 0
  taizaxua5652: 0
  haongu1592k8: 0
  hreinas: 0
  hkyt19: 0
  bananik6406: 0
  hiepsicodon: 0
  datsiudz: 0
  jolunglay: 0
  minhkha12: 0
  ahihiz: 0
  minhphuc2692: 0
  justthais2008: 0
  huy30cm: 0
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 31
  jackthngaming41: 0
  kem_onii_chann: 0
  nglamvn: 0
  binrongvn: 1
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 0
  tuankhanh01: 0
  huyasics: 0
  ngothienquan860: 0
  meonho1502: 0
  nonhercules2394: 0
  cacutexiu: 0
  phophuc: 0
  dz_gaming66: 0
- blackpmfury: 0
  sealonggaming: 0
  jose9543: 1
  kayne6162: 0
  phuongaz: 0
  ailanhan: 4
  icecream1073: 0
  kedoki2579: 6
  dbgamingvn2: 4
  taizaxua5652: 2
  haongu1592k8: 0
  hreinas: 0
  hkyt19: 2
  bananik6406: 0
  hiepsicodon: 5
  datsiudz: 2
  jolunglay: 0
  minhkha12: 4
  ahihiz: 3
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 5
  bananikyt: 0
  shiftyamoeba829: 0
  fitgof14: 1
  jackthngaming41: 0
  kem_onii_chann: 0
  nglamvn: 0
  binrongvn: 1
  shadowmarlin319: 0
  truongmc95: 0
  devilxmc2768: 1
  tuankhanh01: 4
  huyasics: 0
  ngothienquan860: 0
  meonho1502: 0
  nonhercules2394: 1
  cacutexiu: 0
  phophuc: 0
  dz_gaming66: 0
level:
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 5
  dbgamingvn2: 2
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 6
  hkyt19: 1
  bananik6406: 6
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 3
  ahihiz: 2
  minhphuc2692: 2
  justthais2008: 1
  huy30cm: 4
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 2
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 1
  dbgamingvn2: 2
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 3
  hkyt19: 1
  bananik6406: 2
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 3
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 1
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 2
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 1
  dbgamingvn2: 1
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 1
  hkyt19: 1
  bananik6406: 1
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 1
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 1
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 4
  phuongaz: 1
  ailanhan: 9
  icecream1073: 6
  kedoki2579: 9
  dbgamingvn2: 6
  taizaxua5652: 3
  haongu1592k8: 3
  hreinas: 1
  hkyt19: 1
  bananik6406: 7
  hiepsicodon: 1
  datsiudz: 10
  jolunglay: 1
  minhkha12: 4
  ahihiz: 5
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 10
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 2
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 2
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 1
  dbgamingvn2: 1
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 1
  hkyt19: 1
  bananik6406: 1
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 1
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 1
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 1
  dbgamingvn2: 1
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 1
  hkyt19: 1
  bananik6406: 1
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 1
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 1
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 2
  jose9543: 5
  kayne6162: 1
  phuongaz: 1
  ailanhan: 4
  icecream1073: 2
  kedoki2579: 6
  dbgamingvn2: 1
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 6
  hkyt19: 1
  bananik6406: 7
  hiepsicodon: 1
  datsiudz: 4
  jolunglay: 1
  minhkha12: 3
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 2
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 2
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 1
  dbgamingvn2: 1
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 1
  hkyt19: 1
  bananik6406: 1
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 1
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 1
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 1
  dbgamingvn2: 1
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 1
  hkyt19: 1
  bananik6406: 1
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 1
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 1
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
- blackpmfury: 1
  sealonggaming: 1
  jose9543: 1
  kayne6162: 1
  phuongaz: 1
  ailanhan: 1
  icecream1073: 1
  kedoki2579: 1
  dbgamingvn2: 1
  taizaxua5652: 1
  haongu1592k8: 1
  hreinas: 1
  hkyt19: 1
  bananik6406: 1
  hiepsicodon: 1
  datsiudz: 1
  jolunglay: 1
  minhkha12: 1
  ahihiz: 1
  minhphuc2692: 1
  justthais2008: 1
  huy30cm: 1
  bananikyt: 1
  shiftyamoeba829: 1
  fitgof14: 1
  jackthngaming41: 1
  kem_onii_chann: 1
  nglamvn: 1
  binrongvn: 1
  shadowmarlin319: 1
  truongmc95: 1
  devilxmc2768: 1
  tuankhanh01: 1
  huyasics: 1
  ngothienquan860: 1
  meonho1502: 1
  nonhercules2394: 1
  cacutexiu: 1
  phophuc: 1
  dz_gaming66: 1
...
